### PR TITLE
Added Quack

### PR DESCRIPTION
**Pull request by V3rB0se**
A tool to provide denial of service attacks written in python.

### CODE REVIEW

**Comment by V3rB0se** [comment]
my bad its a mini project repo i wish i could contribute with a mini project

**Comment by RK1905101** [comment]
> my bad its a mini project repo i wish i could contribute with a mini project

You can actually add these if you want to.
It is not particularly only based upon mini projects
you can add it :)

**Comment by V3rB0se** [comment]
Sorry i was busy tinkering with the linux kernel. If you think i can add the project I'll create a new pull request. anyway this project is not mine.

**Comment by RK1905101** [comment]
as you wish.
if you want to contribute
you may contribute 
thanks :)
have a good day

**Pull request closed without merging**
