### PR TITLE
Air Canvas (Python)

### PR DESCRIPTION
**Pull request by harshaparida**
result
This is a Python mini project through which we can write on our screen by waving our hands.

### CODE REVIEW

**Comment by RK1905101** [comment]
Air canvas or virtual board you can also count this project under your major project in college.
This is a good one.
Thankyou for your valuable contribution to this repository.
Have a great future ahead :D

**Comment by harshaparida** [comment]
Thank you for your appreciation! I'm excited to hear that you liked the
project. I'm looking forward to working on many more projects like this and
would love to continue contributing to this repository. Have a great future
ahead as well!

**Comment by RK1905101** [comment]
Glad to hear about your interests, project, and contributions to this repository.
Thank you for your wishes.
You can ping me, if needed for any future guidance.
Happy future endeavors!

**Comment by harshaparida** [comment]
Thank you and I will.

**Pull request merged**
